/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv1ActivityPayload {
    #[serde(rename = "memoComment", skip_serializing_if = "Option::is_none")]
    pub memo_comment: Option<Box<models::Apiv1ActivityMemoCommentPayload>>,
    #[serde(rename = "versionUpdate", skip_serializing_if = "Option::is_none")]
    pub version_update: Option<Box<models::Apiv1ActivityVersionUpdatePayload>>,
}

impl Apiv1ActivityPayload {
    pub fn new() -> Apiv1ActivityPayload {
        Apiv1ActivityPayload {
            memo_comment: None,
            version_update: None,
        }
    }
}

