/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv1WorkspaceCustomProfile {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "logoUrl", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "appearance", skip_serializing_if = "Option::is_none")]
    pub appearance: Option<String>,
}

impl Apiv1WorkspaceCustomProfile {
    pub fn new() -> Apiv1WorkspaceCustomProfile {
        Apiv1WorkspaceCustomProfile {
            title: None,
            description: None,
            logo_url: None,
            locale: None,
            appearance: None,
        }
    }
}

