/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv1ActivityVersionUpdatePayload {
    /// The updated version of memos.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl Apiv1ActivityVersionUpdatePayload {
    pub fn new() -> Apiv1ActivityVersionUpdatePayload {
        Apiv1ActivityVersionUpdatePayload {
            version: None,
        }
    }
}

