/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv1IdentityProviderConfig {
    #[serde(rename = "oauth2Config", skip_serializing_if = "Option::is_none")]
    pub oauth2_config: Option<Box<models::Apiv1OAuth2Config>>,
}

impl Apiv1IdentityProviderConfig {
    pub fn new() -> Apiv1IdentityProviderConfig {
        Apiv1IdentityProviderConfig {
            oauth2_config: None,
        }
    }
}

