/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apiv1WorkspaceMemoRelatedSetting {
    /// disallow_public_visibility disallows set memo as public visibility.
    #[serde(rename = "disallowPublicVisibility", skip_serializing_if = "Option::is_none")]
    pub disallow_public_visibility: Option<bool>,
    /// display_with_update_time orders and displays memo with update time.
    #[serde(rename = "displayWithUpdateTime", skip_serializing_if = "Option::is_none")]
    pub display_with_update_time: Option<bool>,
    /// content_length_limit is the limit of content length. Unit is byte.
    #[serde(rename = "contentLengthLimit", skip_serializing_if = "Option::is_none")]
    pub content_length_limit: Option<i32>,
    /// enable_auto_compact enables auto compact for large content.
    #[serde(rename = "enableAutoCompact", skip_serializing_if = "Option::is_none")]
    pub enable_auto_compact: Option<bool>,
    /// enable_double_click_edit enables editing on double click.
    #[serde(rename = "enableDoubleClickEdit", skip_serializing_if = "Option::is_none")]
    pub enable_double_click_edit: Option<bool>,
    /// enable_link_preview enables links preview.
    #[serde(rename = "enableLinkPreview", skip_serializing_if = "Option::is_none")]
    pub enable_link_preview: Option<bool>,
    /// enable_comment enables comment.
    #[serde(rename = "enableComment", skip_serializing_if = "Option::is_none")]
    pub enable_comment: Option<bool>,
}

impl Apiv1WorkspaceMemoRelatedSetting {
    pub fn new() -> Apiv1WorkspaceMemoRelatedSetting {
        Apiv1WorkspaceMemoRelatedSetting {
            disallow_public_visibility: None,
            display_with_update_time: None,
            content_length_limit: None,
            enable_auto_compact: None,
            enable_double_click_edit: None,
            enable_link_preview: None,
            enable_comment: None,
        }
    }
}

