/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Apiv1IdentityProviderType {
    #[serde(rename = "TYPE_UNSPECIFIED")]
    TypeUnspecified,
    #[serde(rename = "OAUTH2")]
    Oauth2,

}

impl std::fmt::Display for Apiv1IdentityProviderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TypeUnspecified => write!(f, "TYPE_UNSPECIFIED"),
            Self::Oauth2 => write!(f, "OAUTH2"),
        }
    }
}

impl Default for Apiv1IdentityProviderType {
    fn default() -> Apiv1IdentityProviderType {
        Self::TypeUnspecified
    }
}

