/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ListNodeKind {
    #[serde(rename = "KIND_UNSPECIFIED")]
    KindUnspecified,
    #[serde(rename = "ORDERED")]
    Ordered,
    #[serde(rename = "UNORDERED")]
    Unordered,
    #[serde(rename = "DESCRIPTION")]
    Description,

}

impl std::fmt::Display for ListNodeKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::KindUnspecified => write!(f, "KIND_UNSPECIFIED"),
            Self::Ordered => write!(f, "ORDERED"),
            Self::Unordered => write!(f, "UNORDERED"),
            Self::Description => write!(f, "DESCRIPTION"),
        }
    }
}

impl Default for ListNodeKind {
    fn default() -> ListNodeKind {
        Self::KindUnspecified
    }
}

