/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemoServiceRenameMemoTagBody {
    #[serde(rename = "oldTag", skip_serializing_if = "Option::is_none")]
    pub old_tag: Option<String>,
    #[serde(rename = "newTag", skip_serializing_if = "Option::is_none")]
    pub new_tag: Option<String>,
}

impl MemoServiceRenameMemoTagBody {
    pub fn new() -> MemoServiceRenameMemoTagBody {
        MemoServiceRenameMemoTagBody {
            old_tag: None,
            new_tag: None,
        }
    }
}

