/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingIsTheSettingToUpdate {
    #[serde(rename = "generalSetting", skip_serializing_if = "Option::is_none")]
    pub general_setting: Option<Box<models::Apiv1WorkspaceGeneralSetting>>,
    #[serde(rename = "storageSetting", skip_serializing_if = "Option::is_none")]
    pub storage_setting: Option<Box<models::Apiv1WorkspaceStorageSetting>>,
    #[serde(rename = "memoRelatedSetting", skip_serializing_if = "Option::is_none")]
    pub memo_related_setting: Option<Box<models::Apiv1WorkspaceMemoRelatedSetting>>,
}

impl SettingIsTheSettingToUpdate {
    pub fn new() -> SettingIsTheSettingToUpdate {
        SettingIsTheSettingToUpdate {
            general_setting: None,
            storage_setting: None,
            memo_related_setting: None,
        }
    }
}

