/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserRole {
    #[serde(rename = "ROLE_UNSPECIFIED")]
    RoleUnspecified,
    #[serde(rename = "HOST")]
    Host,
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "USER")]
    User,

}

impl std::fmt::Display for UserRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RoleUnspecified => write!(f, "ROLE_UNSPECIFIED"),
            Self::Host => write!(f, "HOST"),
            Self::Admin => write!(f, "ADMIN"),
            Self::User => write!(f, "USER"),
        }
    }
}

impl Default for UserRole {
    fn default() -> UserRole {
        Self::RoleUnspecified
    }
}

