/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AutoLinkNode {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "isRawText", skip_serializing_if = "Option::is_none")]
    pub is_raw_text: Option<bool>,
}

impl V1AutoLinkNode {
    pub fn new() -> V1AutoLinkNode {
        V1AutoLinkNode {
            url: None,
            is_raw_text: None,
        }
    }
}

