/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1InboxStatus {
    #[serde(rename = "STATUS_UNSPECIFIED")]
    StatusUnspecified,
    #[serde(rename = "UNREAD")]
    Unread,
    #[serde(rename = "ARCHIVED")]
    Archived,

}

impl std::fmt::Display for V1InboxStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StatusUnspecified => write!(f, "STATUS_UNSPECIFIED"),
            Self::Unread => write!(f, "UNREAD"),
            Self::Archived => write!(f, "ARCHIVED"),
        }
    }
}

impl Default for V1InboxStatus {
    fn default() -> V1InboxStatus {
        Self::StatusUnspecified
    }
}

