/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListInboxesResponse {
    #[serde(rename = "inboxes", skip_serializing_if = "Option::is_none")]
    pub inboxes: Option<Vec<models::V1Inbox>>,
}

impl V1ListInboxesResponse {
    pub fn new() -> V1ListInboxesResponse {
        V1ListInboxesResponse {
            inboxes: None,
        }
    }
}

