/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListMemoPropertiesResponse {
    #[serde(rename = "entities", skip_serializing_if = "Option::is_none")]
    pub entities: Option<Vec<models::V1MemoPropertyEntity>>,
}

impl V1ListMemoPropertiesResponse {
    pub fn new() -> V1ListMemoPropertiesResponse {
        V1ListMemoPropertiesResponse {
            entities: None,
        }
    }
}

