/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListIdentityProvidersResponse {
    #[serde(rename = "identityProviders", skip_serializing_if = "Option::is_none")]
    pub identity_providers: Option<Vec<models::Apiv1IdentityProvider>>,
}

impl V1ListIdentityProvidersResponse {
    pub fn new() -> V1ListIdentityProvidersResponse {
        V1ListIdentityProvidersResponse {
            identity_providers: None,
        }
    }
}

