/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListMemosResponse {
    #[serde(rename = "memos", skip_serializing_if = "Option::is_none")]
    pub memos: Option<Vec<models::V1Memo>>,
    /// A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl V1ListMemosResponse {
    pub fn new() -> V1ListMemosResponse {
        V1ListMemosResponse {
            memos: None,
            next_page_token: None,
        }
    }
}

