/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListNode {
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<models::ListNodeKind>,
    #[serde(rename = "indent", skip_serializing_if = "Option::is_none")]
    pub indent: Option<i32>,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::V1Node>>,
}

impl V1ListNode {
    pub fn new() -> V1ListNode {
        V1ListNode {
            kind: None,
            indent: None,
            children: None,
        }
    }
}

