/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListMemoTagsResponse {
    /// tag_amounts is the amount of tags. key is the tag name. e.g. \"tag1\". value is the amount of the tag.
    #[serde(rename = "tagAmounts", skip_serializing_if = "Option::is_none")]
    pub tag_amounts: Option<std::collections::HashMap<String, i32>>,
}

impl V1ListMemoTagsResponse {
    pub fn new() -> V1ListMemoTagsResponse {
        V1ListMemoTagsResponse {
            tag_amounts: None,
        }
    }
}

