/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ListMemoCommentsResponse {
    #[serde(rename = "memos", skip_serializing_if = "Option::is_none")]
    pub memos: Option<Vec<models::V1Memo>>,
}

impl V1ListMemoCommentsResponse {
    pub fn new() -> V1ListMemoCommentsResponse {
        V1ListMemoCommentsResponse {
            memos: None,
        }
    }
}

