/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MemoRelation {
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "relatedMemo", skip_serializing_if = "Option::is_none")]
    pub related_memo: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::V1MemoRelationType>,
}

impl V1MemoRelation {
    pub fn new() -> V1MemoRelation {
        V1MemoRelation {
            memo: None,
            related_memo: None,
            r#type: None,
        }
    }
}

