/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MemoPropertyEntity {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<Box<models::V1MemoProperty>>,
    #[serde(rename = "displayTime", skip_serializing_if = "Option::is_none")]
    pub display_time: Option<String>,
}

impl V1MemoPropertyEntity {
    pub fn new() -> V1MemoPropertyEntity {
        V1MemoPropertyEntity {
            name: None,
            property: None,
            display_time: None,
        }
    }
}

