/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1MemoRelationType {
    #[serde(rename = "TYPE_UNSPECIFIED")]
    TypeUnspecified,
    #[serde(rename = "REFERENCE")]
    Reference,
    #[serde(rename = "COMMENT")]
    Comment,

}

impl std::fmt::Display for V1MemoRelationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TypeUnspecified => write!(f, "TYPE_UNSPECIFIED"),
            Self::Reference => write!(f, "REFERENCE"),
            Self::Comment => write!(f, "COMMENT"),
        }
    }
}

impl Default for V1MemoRelationType {
    fn default() -> V1MemoRelationType {
        Self::TypeUnspecified
    }
}

