/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1RowStatus {
    #[serde(rename = "ROW_STATUS_UNSPECIFIED")]
    RowStatusUnspecified,
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "ARCHIVED")]
    Archived,

}

impl std::fmt::Display for V1RowStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RowStatusUnspecified => write!(f, "ROW_STATUS_UNSPECIFIED"),
            Self::Active => write!(f, "ACTIVE"),
            Self::Archived => write!(f, "ARCHIVED"),
        }
    }
}

impl Default for V1RowStatus {
    fn default() -> V1RowStatus {
        Self::RowStatusUnspecified
    }
}

