/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1StringifyMarkdownNodesResponse {
    #[serde(rename = "plainText", skip_serializing_if = "Option::is_none")]
    pub plain_text: Option<String>,
}

impl V1StringifyMarkdownNodesResponse {
    pub fn new() -> V1StringifyMarkdownNodesResponse {
        V1StringifyMarkdownNodesResponse {
            plain_text: None,
        }
    }
}

