/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TableNode {
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<Vec<models::V1Node>>,
    #[serde(rename = "delimiter", skip_serializing_if = "Option::is_none")]
    pub delimiter: Option<Vec<String>>,
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::TableNodeRow>>,
}

impl V1TableNode {
    pub fn new() -> V1TableNode {
        V1TableNode {
            header: None,
            delimiter: None,
            rows: None,
        }
    }
}

