/*
 * Memos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V1Visibility {
    #[serde(rename = "VISIBILITY_UNSPECIFIED")]
    VisibilityUnspecified,
    #[serde(rename = "PRIVATE")]
    Private,
    #[serde(rename = "PROTECTED")]
    Protected,
    #[serde(rename = "PUBLIC")]
    Public,

}

impl std::fmt::Display for V1Visibility {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::VisibilityUnspecified => write!(f, "VISIBILITY_UNSPECIFIED"),
            Self::Private => write!(f, "PRIVATE"),
            Self::Protected => write!(f, "PROTECTED"),
            Self::Public => write!(f, "PUBLIC"),
        }
    }
}

impl Default for V1Visibility {
    fn default() -> V1Visibility {
        Self::VisibilityUnspecified
    }
}

